version: '3.8'

services:
  app:
    image: node-webapp:latest
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_NAME=app_database
      - DB_HOST=db
      - DIALECT=mysql
      - PORT=3000
      - NODE_ENV=development
    networks:
      - clouddemo
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app_database
    networks:
      - clouddemo
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 40s

networks:
  clouddemo: