version: '3.8'

services:
  app:
    image: clouddemogo:latest
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=app_database
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_HOST=db
      - DB_PORT=3306
      - DB_PARAMS=charset=utf8mb4&parseTime=True&loc=Local
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    networks:
      - clouddemo
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  psql:
    image: postgres:14
    environment:
      - POSTGRES_DB=app_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"

networks:
  clouddemo:

volumes:
  db_data: