version: '3.8'

services:
  app:
    image: clouddemogo:latest
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_NAME=app_database
      - DB_HOST=db
      - DIALECT=mysql
      - PORT=3000
      - NODE_ENV=development
    networks:
      - clouddemo
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  psql:
    image: postgres:14
    environment:
      - POSTGRES_DB=app_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"
    networks:
      - clouddemo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  clouddemo: